// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz-GM1HqPt9QMzrgT-eoHUjnD9hc5hwTA',
    appId: '1:292178276043:web:e0372f4c1280235e8a354e',
    messagingSenderId: '292178276043',
    projectId: 'first-flutter-notes-ap',
    authDomain: 'first-flutter-notes-ap.firebaseapp.com',
    storageBucket: 'first-flutter-notes-ap.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaJAAA_Koh3Ba8nf8u5rf9Ole0LuE-Pbs',
    appId: '1:292178276043:android:9441d4466dca6f3b8a354e',
    messagingSenderId: '292178276043',
    projectId: 'first-flutter-notes-ap',
    storageBucket: 'first-flutter-notes-ap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjOKM7gye2ryywXNHaw4Xlo6v4QBF6E7s',
    appId: '1:292178276043:ios:9a04c62e416383ec8a354e',
    messagingSenderId: '292178276043',
    projectId: 'first-flutter-notes-ap',
    storageBucket: 'first-flutter-notes-ap.firebasestorage.app',
    androidClientId:
        '292178276043-pdpm3frpr7sb5dvqr6heh15mppukh6l5.apps.googleusercontent.com',
    iosClientId:
        '292178276043-dote08gmuce19o2u73vhvg2a9i79hvu5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjOKM7gye2ryywXNHaw4Xlo6v4QBF6E7s',
    appId: '1:292178276043:ios:9a04c62e416383ec8a354e',
    messagingSenderId: '292178276043',
    projectId: 'first-flutter-notes-ap',
    storageBucket: 'first-flutter-notes-ap.firebasestorage.app',
    androidClientId:
        '292178276043-pdpm3frpr7sb5dvqr6heh15mppukh6l5.apps.googleusercontent.com',
    iosClientId:
        '292178276043-dote08gmuce19o2u73vhvg2a9i79hvu5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myLearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz-GM1HqPt9QMzrgT-eoHUjnD9hc5hwTA',
    appId: '1:292178276043:web:9bb22b2ecf41afc88a354e',
    messagingSenderId: '292178276043',
    projectId: 'first-flutter-notes-ap',
    authDomain: 'first-flutter-notes-ap.firebaseapp.com',
    storageBucket: 'first-flutter-notes-ap.firebasestorage.app',
  );
}
